#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_test_vectors_n4096.py -- generate N=4096 test vectors for the R1.9
on-silicon equivalence test, from the CWRU healthy files (97-100.mat).

Uses the Python oracle (PyWavelets float64, N=4096, J=9). Produces:
  - test_vectors.npz   : segments (float32) + zmax/vstar/alarm annotations
  - constants.h        : E_REF[9] + DET_THRESHOLD (to merge into the firmware)
  - detector_params_n4096.json : E_ref + threshold for reference

NOTE: the firmware header also needs DET_H_SAIN (entropy constant, used only by
the rho_pred output, not by z_max). Keep the existing DET_H_SAIN value; this
script does not regenerate it.
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pywt
from scipy.io import loadmat

N_SEG = 4096
J = 9
MAD_K = 3.0


def haar_wavedec(x, level):
    coeffs = pywt.wavedec(x.astype(np.float64), "haar", level=level)
    return coeffs[1:][::-1]  # [cD1, ..., cDJ], fine-first


def energies(d):
    return np.array([np.mean(dj.astype(np.float64) ** 2) for dj in d])


def detect(x, E_ref):
    E = energies(haar_wavedec(x, J))
    z = (E - E_ref) / E_ref
    z_max = float(np.max(z))
    v_star = int(np.argmax(z)) + 1  # 1-indexed, as in C
    return z_max, v_star


def load_cwru(mat_path):
    m = loadmat(str(mat_path))
    for k, v in m.items():
        if k.startswith("__"):
            continue
        if "DE_time" in k:
            a = np.asarray(v).ravel()
            n = len(a) // N_SEG
            return a[: n * N_SEG].reshape(n, N_SEG).astype(np.float64)
    raise ValueError(f"no DE_time signal in {mat_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cwru_dir", default=r"C:\Users\buisson\CWRU")
    ap.add_argument("--out", default="test_vectors.npz")
    args = ap.parse_args()

    files = ["97.mat", "98.mat", "99.mat", "100.mat"]
    segs = []
    for f in files:
        p = Path(args.cwru_dir) / f
        if p.exists():
            segs.append(load_cwru(p))
        else:
            print(f"  (skip) {f} not found")
    if not segs:
        raise SystemExit("no CWRU healthy files found")
    segs = np.concatenate(segs)

    all_E = np.array([energies(haar_wavedec(s, J)) for s in segs])
    E_ref = np.median(all_E, axis=0)

    zmax_all = np.array([detect(s, E_ref)[0] for s in segs])
    med = float(np.median(zmax_all))
    mad = float(np.median(np.abs(zmax_all - med)))
    thr = med + MAD_K * mad

    zmax_list, vstar_list, alarm_list = [], [], []
    for s in segs:
        zm, vs = detect(s, E_ref)
        zmax_list.append(zm)
        vstar_list.append(vs)
        alarm_list.append(zm > thr)

    np.savez(args.out,
             segments=segs.astype(np.float32),
             zmax=np.array(zmax_list, dtype=np.float32),
             vstar=np.array(vstar_list, dtype=np.uint8),
             alarm=np.array(alarm_list, dtype=bool),
             labels=np.zeros(len(segs), dtype=np.uint8))

    with open("constants.h", "w") as f:
        f.write(f"/* constants.h -- generated by make_test_vectors_n4096.py\n")
        f.write(f"   N={N_SEG}  J={J}  threshold=median+{MAD_K}*MAD  source=CWRU */\n")
        f.write("#ifndef DETECTOR_CONSTANTS_H\n#define DETECTOR_CONSTANTS_H\n\n")
        f.write(f"#define DET_N_SEG  {N_SEG}U\n")
        f.write(f"#define DET_J      {J}U\n\n")
        f.write("/* E_REF[0] = level j=1 (fine) .. E_REF[8] = level j=9 (coarse) */\n")
        f.write("static const float E_REF[DET_J] = {\n")
        f.write(",\n".join(f"    {v:.10e}f  /* j={i+1} */" for i, v in enumerate(E_ref)))
        f.write("\n};\n\n")
        f.write(f"static const float DET_THRESHOLD = {thr:.10e}f;\n\n")
        f.write("/* Entropy constant (used only by rho_pred, not by z_max): keep the\n")
        f.write("   existing firmware value; it does not affect the injection test. */\n")
        f.write("#define DET_H_SAIN  2.4790663f\n\n")
        f.write("#endif /* DETECTOR_CONSTANTS_H */\n")

    with open("detector_params_n4096.json", "w") as f:
        json.dump({"N_SEG": N_SEG, "J": J, "MAD_K": MAD_K,
                   "E_ref": E_ref.tolist(), "threshold": thr}, f, indent=2)

    print(f"n_segments={len(segs)}  threshold={thr:.4f}")
    print(f"E_ref = {E_ref}")
    print(f"-> {args.out}, constants.h, detector_params_n4096.json")


if __name__ == "__main__":
    main()
